
CREATE DATABASE IF NOT EXISTS DavidBotton;
USE DavidBotton;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'client') NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS rendezvous (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    description TEXT,
    date DATE NOT NULL,
    start_hour TIME NOT NULL,
    end_hour TIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB AUTO_INCREMENT=100;

CREATE TABLE IF NOT EXISTS conge (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=150;
